# axolotl submission script

name = test_pin

log = $(name).log
error = $(name).err
output = $(name).out

# VM_TYPE = kvm

# executable = test_pin.sh
executable = /usr/bin/hostname 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = perfect, pin

request_cpus = 1
request_memory = 8GB
request_disk = 8GB

# notify_user = zhewen.pan@wisc.edu
# notification = always

queue 1